src/binutils-config: reformat
Signed-off-by: Allen-Kristjan Päll <akpall@fst.ee>

diff --git a/src/binutils-config b/src/binutils-config
--- a/src/binutils-config
+++ b/src/binutils-config
@@ -27,7 +27,10 @@ source ${FUNCTIONS_SH} || {
 	exit 1
 }
 esyslog() { :; }
-die() { eerror "${argv0}: $*"; exit 1; }
+die() {
+	eerror "${argv0}: $*"
+	exit 1
+}
 umask 022
 
 # *BSD SED does not work as-is, use GNU SED. TODO: find details.
@@ -35,7 +38,7 @@ SED=$(type -P gsed)
 : "${SED:=$(type -P sed)}"
 
 usage() {
-cat << USAGE_END
+	cat <<USAGE_END
 Usage: ${HILITE}binutils-config${NORMAL} ${GOOD}[options]${NORMAL} ${BRACKET}[binutils profile]${NORMAL}
 
 ${HILITE}General Options:${NORMAL}
@@ -53,7 +56,7 @@ ${HILITE}General Options:${NORMAL}
  ${GOOD}                           ${NORMAL} profile are located.
 
 Profile names are of the form: ${BRACKET} <CTARGET>-<binutils version>${NORMAL}, ${BRACKET}latest${NORMAL},
-                               ${BRACKET} <CTARGET>-latest${NORMAL}, ${BRACKET}latest${NORMAL}.
+			       ${BRACKET} <CTARGET>-latest${NORMAL}, ${BRACKET}latest${NORMAL}.
 For example:                   ${BRACKET} i686-pc-linux-gnu-2.15.92.0.2${NORMAL}
 
 For more info, please see ${HILITE}binutils-config${NORMAL}(8).
@@ -74,26 +77,28 @@ version_sorted_paths() {
 	local p mangled_v
 	for p in "$@"; do
 		# TODO: avoid -r
-		mangled_v=$(printf "%s" "${p}" |
-			${SED} -e 's/[0-9]\+/0000&/g' |
-			${SED} -e 's/0*\([0-9]\{4\}\)/\1/g'
+		mangled_v=$(
+			printf "%s" "${p}" |
+				${SED} -e 's/[0-9]\+/0000&/g' |
+				${SED} -e 's/0*\([0-9]\{4\}\)/\1/g'
 		)
 		printf "%s %s\n" "${mangled_v}" "${p}"
 	done | LANG=C sort | $SED -e 's/^.* //g'
 }
 
 mv_if_diff() {
-	if cmp -s "$1" "$2" ; then
+	if cmp -s "$1" "$2"; then
 		rm -f "$1"
 	else
 		mv -f "$1" "$2"
 	fi
 }
+
 atomic_ln() {
 	local target=$1 linkdir=$2 linkname=$3 linktmp linkfull
 	linktmp="${linkdir}/.binutils-config.tmp.${linkname}"
 	linkfull="${linkdir}/${linkname}"
-	if [[ -d ${linkfull} ]] ; then
+	if [[ -d ${linkfull} ]]; then
 		# if linking to a dir, we need a little magic to
 		# make it atomic since `mv -T` is not portable
 		rm -rf "${linktmp}"
@@ -114,11 +119,11 @@ setup_env() {
 	unset TARGET VER LIBPATH
 	# shellcheck disable=SC1090
 	source "${ENV_D}/${PROFILE}"
-	if [[ -z ${TARGET} ]] ; then
+	if [[ -z ${TARGET} ]]; then
 		eerror "${PROFILE} is invalid (no \$TARGET defined) :("
 		return 1
 	fi
-	if [[ -z ${VER} ]] ; then
+	if [[ -z ${VER} ]]; then
 		eerror "${PROFILE} is invalid (no \$VER defined) :("
 		return 1
 	fi
@@ -128,17 +133,17 @@ setup_env() {
 	#
 	BINPATH=""
 	BINPATH_LINKS=""
-	if [[ ${TARGET} != "${HOST}" ]] ; then
+	if [[ ${TARGET} != "${HOST}" ]]; then
 		#
 		# Newer paths: /usr/${HOST}/${TARGET}/...
 		# Older paths: /usr/${TARGET}/...
 		#
-		if [[ -d "${EROOT}"/usr/${HOST}/${TARGET}/binutils-bin/${VER} ]] ; then
+		if [[ -d "${EROOT}"/usr/${HOST}/${TARGET}/binutils-bin/${VER} ]]; then
 			BINPATH="${EPREFIX}"/usr/${HOST}/${TARGET}/binutils-bin/${VER}
 			BINPATH_LINKS="${EPREFIX}"/usr/libexec/gcc/${TARGET}
 		fi
 	fi
-	if [[ -z ${BINPATH} ]] ; then
+	if [[ -z ${BINPATH} ]]; then
 		BINPATH="${EPREFIX}"/usr/${TARGET}/binutils-bin/${VER}
 		BINPATH_LINKS="${EPREFIX}"/usr/${TARGET}/bin
 	fi
@@ -175,10 +180,10 @@ switch_profile() {
 
 	local bad_symlinks_removed="0"
 
-	for x in * ; do
+	for x in *; do
 		atomic_ln "${BINPATH}/${x}" "${ROOT}/${BINPATH_LINKS}" "${x}"
 		atomic_ln "${BINPATH_LINKS}/${x}" "${EROOT}/usr/bin" "${TARGET}-${x}"
-		if [[ ${TARGET} == "${HOST}" ]] ; then
+		if [[ ${TARGET} == "${HOST}" ]]; then
 			if [[ ${USE_NATIVE_LINKS} == yes ]]; then
 				atomic_ln "${TARGET}-${x}" "${EROOT}/usr/bin" "${x}"
 			else
@@ -195,14 +200,14 @@ switch_profile() {
 			# Some stages errorneously could not figure out CHOST and installed
 			# symlinks into the path ${EROOT}/usr/libexec/gcc/${HOST}. These need
 			# to go away.
-			if [[ -h "${EROOT}/usr/libexec/gcc/${HOST}/${x}" ]] ; then
+			if [[ -L "${EROOT}/usr/libexec/gcc/${HOST}/${x}" ]]; then
 				rm -f "${EROOT}/usr/libexec/gcc/${HOST}/${x}"
 				bad_symlinks_removed="1"
 			fi
 		fi
 	done
 
-	if [[ ${bad_symlinks_removed} == "1" ]] ; then
+	if [[ ${bad_symlinks_removed} == "1" ]]; then
 		einfo "binutils-config removed errorneous, leftover symlinks in ${EROOT}/usr/libexec/gcc/${HOST}"
 	fi
 
@@ -211,7 +216,7 @@ switch_profile() {
 	#
 	: "${LIBPATH:=${EPREFIX}/usr/lib/binutils/${TARGET}/${VER}}"
 	cd "${ROOT}/${LIBPATH}" || exit 1
-	if [[ ${TARGET} == "${HOST}" ]] ; then
+	if [[ ${TARGET} == "${HOST}" ]]; then
 		dstlib=${EROOT}/usr/${HOST}/lib
 	else
 		dstlib=${EROOT}/usr/${HOST}/${TARGET}/lib
@@ -227,9 +232,9 @@ switch_profile() {
 	# Detect older binutils w/broken rpaths. #562460
 	# We can hardcode the "/lib" part since that's what the binutils
 	# configure scripts have.  They did not include any other path.
-	if [[ $(scanelf -qF '%r#F' "${ROOT}/${BINPATH}/as") == */lib ]] ; then
+	if [[ $(scanelf -qF '%r#F' "${ROOT}/${BINPATH}/as") == */lib ]]; then
 		ewarn "Old cross-binutils detected; please re-emerge to fix (see bug #562460)."
-		for x in lib* ; do
+		for x in lib*; do
 			atomic_ln "${LIBPATH}/${x}" "${dstlib}" "${x}"
 		done
 	fi
@@ -238,14 +243,14 @@ switch_profile() {
 	# Clean out old generated include symlinks
 	#
 	INCPATH=${LIBPATH}/include
-	if [[ -d ${ROOT}/${INCPATH} ]] ; then
+	if [[ -d ${ROOT}/${INCPATH} ]]; then
 		cd "${ROOT}/${INCPATH}" || exit 1
-		if [[ ${HOST} != "${TARGET}" ]] ; then
+		if [[ ${HOST} != "${TARGET}" ]]; then
 			# Clean out old path -- cannot use '-exec {} +' syntax here
 			find . -type f -exec rm -f "${EROOT}/usr/${TARGET}/usr/include/{}" \;
-			rmdir "${EROOT}/usr/${TARGET}/usr/include" >& /dev/null
-			rmdir "${EROOT}/usr/${TARGET}/usr" >& /dev/null
-			rmdir "${EROOT}/usr/${TARGET}" >& /dev/null
+			rmdir "${EROOT}/usr/${TARGET}/usr/include" >&/dev/null
+			rmdir "${EROOT}/usr/${TARGET}/usr" >&/dev/null
+			rmdir "${EROOT}/usr/${TARGET}" >&/dev/null
 		fi
 	fi
 
@@ -253,7 +258,7 @@ switch_profile() {
 	# Make sure proper paths get updated
 	#
 	local env_update_flag="--no-ldconfig"
-	if [[ ${TARGET} == "${HOST}" ]] ; then
+	if [[ ${TARGET} == "${HOST}" ]]; then
 		# Delete old config now that binutils-libs installs these files.
 		# Note: This skips ldconfig update if env.d had LDPATH, but meh.
 		# Most people have upgraded to ld.so.conf.d, and someone else will
@@ -268,14 +273,14 @@ switch_profile() {
 		local e="${EROOT}"/etc/env.d/05binutils
 		local ee="${e}.tmp"
 		rm -f "${ee}"
-		[[ -d ${ROOT}/${DATAPATH}/man  ]] && echo "MANPATH=${DATAPATH}/man"   >> "${ee}"
-		[[ -d ${ROOT}/${DATAPATH}/info ]] && echo "INFOPATH=${DATAPATH}/info" >> "${ee}"
+		[[ -d ${ROOT}/${DATAPATH}/man ]] && echo "MANPATH=${DATAPATH}/man" >>"${ee}"
+		[[ -d ${ROOT}/${DATAPATH}/info ]] && echo "INFOPATH=${DATAPATH}/info" >>"${ee}"
 		[[ -e "${ee}" ]] && mv_if_diff "${ee}" "${e}"
 	fi
 
 	local c="${ENV_D}/config-${TARGET}"
 	local cc="${c}.tmp"
-	echo "CURRENT=${VER}" > "${cc}"
+	echo "CURRENT=${VER}" >"${cc}"
 	mv_if_diff "${cc}" "${c}"
 
 	eend 0
@@ -283,7 +288,7 @@ switch_profile() {
 	#
 	# Regen env.d if need/can be
 	#
-	if [[ ${ROOT} == "/" ]] && [[ ${TARGET} == "${HOST}" ]] ; then
+	if [[ ${ROOT} == "/" ]] && [[ ${TARGET} == "${HOST}" ]]; then
 		env-update ${env_update_flag}
 		echo
 		ewarn "Please remember to run:"
@@ -298,18 +303,18 @@ switch_profile() {
 uninstall_target() {
 	: "${TARGET:=${UARG}}"
 
-	if [[ ${TARGET} == "${HOST}" ]] ; then
+	if [[ ${TARGET} == "${HOST}" ]]; then
 		die "refusing to uninstall native binutils"
 	fi
 
 	shopt -s nullglob
 	PROFILE=""
 
-	for PROFILE in "${ENV_D}"/"${TARGET}"-* ; do
+	for PROFILE in "${ENV_D}"/"${TARGET}"-*; do
 		ewarn "Removing all signs of ${PROFILE##*/}"
 		rm -f "${ENV_D}"/"${PROFILE}"
 	done
-	if [[ -z ${PROFILE} ]] && [[ ! -e ${ENV_D}/config-${TARGET} ]] ; then
+	if [[ -z ${PROFILE} ]] && [[ ! -e ${ENV_D}/config-${TARGET} ]]; then
 		die "no profiles exist for '${TARGET}'"
 	fi
 
@@ -319,8 +324,7 @@ uninstall_target() {
 	for x in \
 		addr2line ar as c++filt dwp elf2flt elfedit flthdr gprof \
 		ld ld.{bfd,gold,real} \
-		nm objcopy objdump ranlib readelf size strings strip
-	do
+		nm objcopy objdump ranlib readelf size strings strip; do
 		x=(
 			"${EROOT}"/usr/bin/"${TARGET}"-"${x}"
 			"${EROOT}"/usr/{${HOST}/,}"${TARGET}"/bin/"${x}"
@@ -328,10 +332,10 @@ uninstall_target() {
 		)
 		rm -f "${x[@]}"
 	done
-	for x in "${HEADERS[@]}" ; do
+	for x in "${HEADERS[@]}"; do
 		rm -f "${EROOT}"/usr/{"${HOST}"/,}"${TARGET}"/{usr/,}include/"${x}"
 	done
-	for x in bfd iberty opcodes ; do
+	for x in bfd iberty opcodes; do
 		rm -f "${EROOT}"/usr/"${HOST}"/"${TARGET}"/lib/lib"${x}"{{-*,}.so,.a,.la}
 	done
 	# Delete broken symlinks
@@ -350,7 +354,7 @@ uninstall_target() {
 }
 
 set_current_profile() {
-	if [[ ! -f ${ENV_D}/config-${TARGET} ]] ; then
+	if [[ ! -f ${ENV_D}/config-${TARGET} ]]; then
 		eerror "${argv0}: unable to locate a profile for target: ${TARGET}"
 		return 1
 	fi
@@ -358,7 +362,7 @@ set_current_profile() {
 	# shellcheck disable=SC1090
 	source "${ENV_D}/config-${TARGET}"
 
-	if [[ -z ${CURRENT} ]] ; then
+	if [[ -z ${CURRENT} ]]; then
 		eerror "${argv0}: no binutils profile is active!"
 		return 1
 	fi
@@ -367,7 +371,7 @@ set_current_profile() {
 
 	return 0
 }
-get_current_profile() { echo "${PROFILE}" ; }
+get_current_profile() { echo "${PROFILE}"; }
 
 get_bin_path() {
 	setup_env || return 1
@@ -382,7 +386,7 @@ get_lib_path() {
 list_profiles() {
 	local x i target
 
-	if [[ ${ROOT} != / ]] ; then
+	if [[ ${ROOT} != / ]]; then
 		echo "Using binutils-config info in ${ROOT}"
 	fi
 
@@ -390,26 +394,26 @@ list_profiles() {
 	target=
 	i=1
 
-	for x ; do
+	for x; do
 		# skip broken links and config files
 		[[ -f ${x} ]] || continue
 		[[ ${x} == */config-* ]] && continue
 
 		# shellcheck disable=SC1090
 		source "${x}"
-		if [[ ${target} != "${TARGET}" ]] ; then
+		if [[ ${target} != "${TARGET}" ]]; then
 			[[ -n ${target} ]] && echo
 			target=${TARGET}
 		fi
 
 		x=${x##*/}
-		if [[ -e ${ENV_D}/config-${TARGET} ]] ; then
+		if [[ -e ${ENV_D}/config-${TARGET} ]]; then
 			# shellcheck disable=SC1090
 			source "${ENV_D}/config-${TARGET}"
-			if [[ ${VER} == "${CURRENT}" ]] ; then
-				[[ ${TARGET} == "${HOST}" ]] \
-					&& x="${x} ${GOOD}*${NORMAL}" \
-					|| x="${x} ${HILITE}*${NORMAL}"
+			if [[ ${VER} == "${CURRENT}" ]]; then
+				[[ ${TARGET} == "${HOST}" ]] &&
+					x="${x} ${GOOD}*${NORMAL}" ||
+					x="${x} ${HILITE}*${NORMAL}"
 			fi
 		fi
 
@@ -432,7 +436,7 @@ set_HOST() {
 	# Set HOST to CHOST if it isn't already set
 	: "${HOST:=${CHOST:-$(portageq envvar CHOST)}}"
 
-	if [[ -z ${HOST} ]] ; then
+	if [[ -z ${HOST} ]]; then
 		eerror "Cannot determine CHOST. Something is badly broken."
 		# once our current stage build problems are fixed, let's enable this:
 		# exit 1
@@ -451,7 +455,7 @@ USE_NATIVE_LINKS="@USE_NATIVE_LINKS@"
 unset UARG
 
 select_action() {
-	if [[ ${NEED_ACTION} != "no" ]] ; then
+	if [[ ${NEED_ACTION} != "no" ]]; then
 		NEED_ACTION="no"
 		DOIT=$1
 	else
@@ -459,35 +463,35 @@ select_action() {
 	fi
 }
 
-while [[ $# -gt 0 ]] ; do
+while [[ $# -gt 0 ]]; do
 	x=$1
 	shift
 	case ${x} in
-		-B|--get-bin-path)         select_action get_bin_path ;;
-		-L|--get-lib-path)         select_action get_lib_path ;;
-		-c|--get-current-profile)  select_action get_current_profile ;;
-		-l|--list|--list-profiles) select_action list_profiles ;;
-		-u|--uninstall)            select_action uninstall_target ;;
-		-C|--nocolor) ;; # nothing to do; functions.sh parsed this for us
-		-d|--debug)                DEBUG="yes" ;;
-		-h|--help)                 usage 0 ;;
-		--enable-native-links)     USE_NATIVE_LINKS="yes" ;;
-		--disable-native-links)    USE_NATIVE_LINKS="no" ;;
-		-V|--version)
-			ver="@PV@"
-			echo "binutils-config-${ver/@'PV'@/git}"
-			exit 0
-			;;
-		-*)
-			die "invalid switch!  Try '--help'."
-			;;
-		*)
-			if [[ ${UARG+set} == "set" ]] ; then
-				die "only one profile/target at a time please"
-			fi
-			NEED_ACTION="maybe"
-			UARG=${x}
-			;;
+	-B | --get-bin-path) select_action get_bin_path ;;
+	-L | --get-lib-path) select_action get_lib_path ;;
+	-c | --get-current-profile) select_action get_current_profile ;;
+	-l | --list | --list-profiles) select_action list_profiles ;;
+	-u | --uninstall) select_action uninstall_target ;;
+	-C | --nocolor) ;; # nothing to do; functions.sh parsed this for us
+	-d | --debug) DEBUG="yes" ;;
+	-h | --help) usage 0 ;;
+	--enable-native-links) USE_NATIVE_LINKS="yes" ;;
+	--disable-native-links) USE_NATIVE_LINKS="no" ;;
+	-V | --version)
+		ver="@PV@"
+		echo "binutils-config-${ver/@'PV'@/git}"
+		exit 0
+		;;
+	-*)
+		die "invalid switch!  Try '--help'."
+		;;
+	*)
+		if [[ ${UARG+set} == "set" ]]; then
+			die "only one profile/target at a time please"
+		fi
+		NEED_ACTION="maybe"
+		UARG=${x}
+		;;
 	esac
 done
 
@@ -504,13 +508,13 @@ switch_profile)
 	# decode user's profile choice
 	x=${UARG:-$(TARGET=${HOST} set_current_profile)}
 	PROFILE=""
-	if [[ -z $(echo "${x}" | tr -d '[:digit:]') ]] ; then
+	if [[ -z $(echo "${x}" | tr -d '[:digit:]') ]]; then
 		# User gave us a profile index number from '--list-profiles'
 		i=1
-		for y in "${ENV_D}"/* ; do
-			[[ ${y/config-} != "${y}" ]] && continue
+		for y in "${ENV_D}"/*; do
+			[[ ${y/config-/} != "${y}" ]] && continue
 
-			if [[ -f ${y} ]] && [[ ${x} -eq ${i} ]] ; then
+			if [[ -f ${y} ]] && [[ ${x} -eq ${i} ]]; then
 				PROFILE=${y##*/}
 				break
 			fi
@@ -518,7 +522,7 @@ switch_profile)
 		done
 	fi
 
-	if [[ -z ${PROFILE} ]] ; then
+	if [[ -z ${PROFILE} ]]; then
 		# User gave us "latest" or "<CTARGET>-latest".
 		if [[ ${x} == latest ]]; then
 			x=$(version_sorted_paths "${ENV_D}"/"${HOST}"-* | tail -1)
@@ -528,14 +532,14 @@ switch_profile)
 
 		# User gave us a full <CTARGET-version>, <CTARGET> or <version>
 		x=${x##*/}
-		if [[ -f ${ENV_D}/${x} ]] ; then
+		if [[ -f ${ENV_D}/${x} ]]; then
 			# Valid <CTARGET-version>
 			PROFILE=${x}
 		else
 			# Not a valid <CTARGET-version>
-			if [[ ! -f ${ENV_D}/config-${x} ]] ; then
+			if [[ ! -f ${ENV_D}/config-${x} ]]; then
 				# Maybe they just gave us a <version>. Infer <CTARGET>.
-				if [[ -f ${ENV_D}/${HOST}-${x} ]] ; then
+				if [[ -f ${ENV_D}/${HOST}-${x} ]]; then
 					x=${HOST}-${x}
 				else
 					die "could not locate '$x' in '${ENV_D}/'!"
